:source-highlighter: highlight.js

= For Loops

For loops allow programmers to perform an action for _every_ element in
a list.

You'll often hear the term *iteration* or *iterator* when `+for+` loops
are mentioned. An *iteration* is a repetition of the code defined within
the `+for+` loop. An *iterator* is a variable helps that keeps track of
where the program is within the list being iterated over.

The syntax for a for loop is:

[source,python]
----
for my_temporary_iterator_variable in my_list:
    #do something
----

The `+my_temporary_iterator_variable+` will have type and value of the
first element in the list, then the second element, and so on.

For example, if we have a list defined as:

[source,python]
----
my_list = ["a string", 2]
----

. The first time the code under the `+for+` loop is executed,
`+my_temporary_iterator_variable+` has a type of `+str+` and a value of
`+"a string"+`. 
. The iteration of the loop,
`+my_temporary_iterator_variable+` has a type of `+int+` and value of
`+2+`.

[IMPORTANT]
====
Remember, indentation is important in python!
====

Source: https://wiki.python.org/moin/ForLoop[python.org]

[source,python]
----
my_list = ["a string", 3, 78.92723, True]
for my_element in my_list:
    print(my_element)
----

....
a string
3
78.92723
True
....

You can also use the elements in a list to create a new list

[source,python]
----
my_number_list = [1, 2, 3, 4]
squares_list = []
for n in my_number_list:
    squares_list.append(n*n)

print(my_number_list)
print(squares_list)
----

....
[1, 2, 3, 4]
[1, 4, 9, 16]
....

<<<

== Using range()

But what if I want to change the elements in the list? That's a little
tricker. You can change the values in a list when using a for loop, but
it is _not_ safe to add or remove elements from a list while in a
`+for+` loop.

We are going to need the help for the range function. The `+range+`
creates a sequence of numbers.

[source,python]
----
for i in range(3):
    print(i)
----

....
0
1
2
....

[source,python]
----
for i in range(4):
    print("*" * i)
----

....

*
**
***
....

The `+range+` creates a sequence of numbers that will allow us to access
each element in a list in order by using `+[]+` to access each element
in the list.

For example `+range(3)+` will create a sequence containing 0,1,2. Just
like splicing lists, `+range()+` creates sequence that starts and zero and
ends at one less than the ending number.

`+range(len(my_list))+` will create a sequence containing `+0+` to
`+len(my_list)-1+`

[source,python]
----
#create squares list in place
my_list = [1, 2, 7, 9]
print(my_list)

for i in range(len(my_list)):
    my_list[i] = my_list[i] * my_list[i]

print(my_list)
----

....
[1, 2, 7, 9]
[1, 4, 49, 81]
....

== Stepping with Range function

The `+range+` function also allows allows for a step to to specified. We
can use the step to create a sequence of even numbers or a descending
sequence.

The function signature is

[source,python]
----
range(start_index, stop_before_index, step)
----

[source,python]
----
# print every 5th index
for i in range(0, 25, 5):
    print(i, end=" ")
----

....
0 5 10 15 20 
....

[source,python]
----
# print 10 to 1 in descending order
for i in range(10, 0, -1):
    print(i, end=" ")
----

....
10 9 8 7 6 5 4 3 2 1 
....

== Breaking out of loops

Just like `+while+` loops we can use the `+break+` and `+continue+`
keywords to interrupt the execution of a loop.

[source,python]
----
my_list = list(range(1, 20))

for current_item in my_list:
    if current_item % 13 == 0:
        print ("!!", end=' ')
        break

    if current_item % 2 == 0:
        print ("**", end=' ')
        continue
        
    print(f"[{current_item}]", end=' ')
----

....
[1] ** [3] ** [5] ** [7] ** [9] ** [11] ** !! 
....

<<<

== Assignments

[[assignment-621---ascii-art]]
=== Assignment 6.2.1 - Ascii art

Create a program that prints:

[source,text]
----
*
**
***
****
***
**
*
----


Create a program that prints:

[source,text]
----
----*----    
---***---
--*****--
-*******-
--*****--
---***---
----*----
----

Pattern is:

[%autowidth]
|===

| 4 dashes | 1 star | 4 dashes

| 3 dashes | 3 stars | 3 dashes

| 2 dashes | 5 stars | 2 dashes

| 1 dashes | 7 stars | 1 dashes

| 2 dashes | 5 stars | 2 dashes

| 3 dashes | 3 stars | 3 dashes

| 4 dashes | 1 stars | 4 dashes

|===

==== Grading

[%autowidth]
[cols=",",options="header",]
|===
|Item |Points
|Half diamond |2
|Full diamond |4
|===

<<<
    
[[assignment-6-2-2]]
=== Assignment 6.2.2 - Min and Max

Given the list below, find the lowest and highest number in the list
without using the `+min(my_list)+` or `+max(my_list)+` functions.

[source,python]
----
my_list = [3.6, 9, 1000, 542.39, 1_583, -123, 435]
----

==== Grading

[%autowidth]
[cols=",",options="header",]
|===
|Item |Points
|Uses `+for+` loop |.5
|Correctly finds min and max |1
|Prints max and min |.5
|===

